# SPDX-License-Identifier: MIT
compatible: "zmk,input-split-ext"  # ← ZMK本体とバッティングしないように名前変更

description: Custom binding for input-split to avoid conflict

include: base.yaml

properties:
  input:
    required: true
    type: phandle
